version: '3'

services:
  client:
    container_name: client
    restart: always
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - '4000:8080'
  api:
    container_name: api
    restart: always
    build: ./server
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'